feat: initial plugin
* feat: hack together basic plugin that adds a test command

* build: ignore sdk jar regardless of name

* build: Hytale lib is now compileOnly

* build: Gradle tasks for automatically setting up a Hytale server

* chore: README update, run/debug configs for IntelliJ

* chore: depend on task reference instead of string

* feat: initial sigil asset & loading

Additionally, we are now using jspecify annotations for nullability checking; no more codegen for package-info (due to using @NullMarked). Update CONTRIBUTING.md accordingly.

Conventions plugin also sets spotless to format json by default, with 2 space indents and no key sorting.

* chore: fix exception format, remove UnknownNullability usage

Add a few new guidelines to CONTRIBUTING.md relating to exception messages.

Documentation tweaks, and making exception messages consistent.

* feat: Once<T> for thread-safe one-time-init statics

Currently used for SigilPattern#ASSET_STORE.

* chore: additional documentation and test for Once

* feat: basic UI triggered by certain chat messages

* build: fix strange issue with resources not getting jarred

* build: support multiple plugins in the project

Also includes proper naming for the archives, corresponding to the chosen plugin name. Dev build task is no longer stored on the `main` subproject.

* build: add --enable-native-access=ALL-UNNAMED to get rid of a warning

* build: add cleanRunDir task

* build: error reporting improvements & extra documentation

* chore: fix up gitignore

* build: fix runDevServer classpath, update cleanRunDir to remove only json files

Also update README.md to document new tasks and clarify that the prerelease version should be used.

* feat: basic working item, item model, and right-click interaction

* fix: slightly larger model for the wand

* chore: minor cleanup

* ci: potentially working setup for building against the Hytale server

Also includes an integration test framework + actually launching the server with the plugin.

* fix: add GH_TOKEN env var and token expiration sanity checks

* fix: remove newlines from output base64

* fix: NPE, better error reporting on bad .hytale contents

* chore: add implementation comments, trim unused files, update workflow actions versions

* build: use hytale maven dependency

* build: use provider for .hytale file as it is not needed for all tasks

Also update documentation and change `build` job to use read permissions.

* build: add tasks to validate that the local Hytale version is the same as Maven one

This task only runs when trying to launch the local development server.

* feat: basic sigil HUD element and interactions

Implementation currently has a few problems with the HUD getting stuck; fix pending.

Also removes the Hytale revisions validation code as it was unnecessary.

* fix: sigil HUD no longer displays incorrectly

* docs: update CONTRIBUTING.md with AI policy, fix README.md

* feat: custom component for maintaining Sigil draw state

Also add generic utility code for handling interactions, update manifest.json to rely on Hytale:EntityModule and Hytale:BlockModule, and split off registration logic from Plugin to a new class Init.

* feat: prototype Sigil drawing

Includes drawable lines in the Sigil HUD grid, erasing by "redrawing" over the previous line, and (incomplete) checks to make sure sigils are actually canonical.

Enable assertions when running the development server.

* chore: rename some things, typo fix, documentation

* feat: optional MHUD support

* fix: use HudUtils in one more location

* feat: improve Sigil drawing cursor

* fix: clean up sigil lines a bit

* fix: checking for sigil point validity in line drawing

Also clean up casting wand model/texture; add Hytale to the unit test runtime classpath

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,10 +17,70 @@ jobs:
       - name: Checkout
         uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # 6.0.1
 
+      # Determines the most up-to-date Hytale server version. Outputs the version string to a file
+      # in `.runner/version`.
+      - name: Determine server version
+        env:
+          HYTALE_DOWNLOADER_CREDENTIALS: ${{ secrets.HYTALE_DOWNLOADER_CREDENTIALS }}
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+
+        # Run `gh secret list` first to immediately fail the build if our GH_TOKEN has expired. This
+        # prevents us from ending up with stale data inside `HYTALE_DOWNLOADER_CREDENTIALS`, since
+        # if the `gh` command fails it means we didn't update the stored value of the secret.
+        run: |
+          gh secret list > /dev/null
+          
+          mkdir .runner && cd .runner
+          printf %s "$HYTALE_DOWNLOADER_CREDENTIALS" | base64 -d > .hytale-downloader-credentials.json
+          wget 'https://downloader.hytale.com/hytale-downloader.zip' -O downloader.zip
+          unzip downloader.zip
+          chmod +x hytale-downloader-linux-amd64
+          
+          set +e
+          ./hytale-downloader-linux-amd64 -skip-update-check -patchline pre-release -print-version > version
+          exit_code=$?
+          set -e
+          
+          base64 -w 0 .hytale-downloader-credentials.json | gh secret set HYTALE_DOWNLOADER_CREDENTIALS
+          exit "$exit_code"
+
+      # Restores the game files from cache, to avoid needing to re-download. Uses the hash of
+      # `.runner/version` as a cache key.
+      - name: Cache server files
+        id: cache-server-files
+        uses: &cache actions/cache@8b402f58fbc84540c8b491a91e594a4576fec3d7 # 5.0.3
+        with:
+          key: hytale-server-files-${{ hashFiles('.runner/version') }}
+          enableCrossOsArchive: true
+          path: |
+            .runner/Assets.zip
+            .runner/Server/HytaleServer.jar
+            .runner/Server/HytaleServer.aot
+
+      # If the above was a cache miss, we have to download a new version of the game to build
+      # against.
+      - name: Download and unzip server files
+        env:
+          GH_TOKEN: ${{ secrets.GH_TOKEN }}
+        if: steps.cache-server-files.outputs.cache-hit != 'true'
+        run: |
+          gh secret list > /dev/null
+          cd .runner
+          
+          set +e
+          ./hytale-downloader-linux-amd64 -skip-update-check -patchline pre-release -download-path game.zip
+          exit_code=$?
+          set -e
+          
+          base64 -w 0 .hytale-downloader-credentials.json | gh secret set HYTALE_DOWNLOADER_CREDENTIALS
+          [ "$exit_code" -eq 0 ] || exit "$exit_code"
+          
+          unzip game.zip
+
       # We need to use a separate cache action for the convention plugin specifically: setup-gradle
       # does NOT do this automatically.
       - name: Cache buildSrc
-        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # 5.0.1
+        uses: *cache
         with:
           # Key is based off of the hash of all the script files, plus the Gradle wrapper.
           key: gradle-buildSrc-${{ hashFiles('buildSrc/*.gradle.kts', 'buildSrc/src/**/*', 'gradle/wrapper/*') }}
@@ -35,7 +95,7 @@ jobs:
             ./buildSrc/build/tmp
 
       - name: Set up JDK 25
-        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # 5.0.1
+        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # 5.2.0
         with:
           java-version: '25'
           distribution: 'temurin'
@@ -51,5 +111,19 @@ jobs:
           # builds.
           cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
 
-      - name: Build Project
-        run: ./gradlew build
+      # `check` runs Spotless and unit tests, `syncPlugins` collects all plugins in the `run`
+      # directory.
+      - name: Run unit tests and assemble plugins
+        run: ./gradlew check syncPlugins
+
+      # Integration tests are run by booting the server and executing the command
+      # `integration_test`. Tests are considered to have failed if this is a non-zero exit code.
+      # Note: in the future, we will also want to add --validate-assets, but at the moment even
+      # vanilla Hytale does not pass their own asset validation checks; we will have to wait.
+      - name: Run integration tests
+        run: |
+          mkdir .runner/Server/mods
+          cp run/mods/*.jar .runner/Server/mods/
+          
+          cd .runner/Server
+          ENABLE_INTEGRATION_TESTS=true java -XX:AOTCache=HytaleServer.aot --enable-native-access=ALL-UNNAMED -jar HytaleServer.jar --assets ../Assets.zip --disable-sentry --auth-mode=insecure --boot-command=integration_test --boot-command=stop
